In [106]:
import tensorflow
from tensorflow.keras.models import load_model
import pickle
import numpy as np
import pandas as pd


In [107]:
#how to load pickle files
model = load_model('model.h5')
with open('label_encoder_gender.pkl','rb')as file:
    label_encoder_gender = pickle.load(file)
with open('onehot_encoder_geo.pkl','rb')as file:
    onehot_encoder_geo = pickle.load(file)
with open('scaler.pkl','rb')as file:
    scaler = pickle.load(file)


In [108]:
input_data = {
    'CreditScore' : 0,
    'Geography':'Germany',
    'Gender':'Male',
    'Age':73,
    'Tenure': 3,
    'Balance': 10,
    'NumOfProducts':0,
    'HasCrCard': 0,
    'IsActiveMember': 0,
    'EstimatedSalary': 5000
}


In [109]:
data = pd.DataFrame([input_data])
data

CreditScore Geography Gender  ...  HasCrCard  IsActiveMember  EstimatedSalary
0            0   Germany   Male  ...          0               0             5000

[1 rows x 10 columns]

In [110]:
data['Gender'] = label_encoder_gender.transform(data['Gender'])


In [111]:
data

CreditScore Geography  Gender  ...  HasCrCard  IsActiveMember  EstimatedSalary
0            0   Germany       1  ...          0               0             5000

[1 rows x 10 columns]

In [112]:
x = onehot_encoder_geo.transform([data['Geography']])
x.toarray()

/home/user/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


array([[0., 1., 0.]])

In [113]:
geo = pd.DataFrame(x.toarray(),columns=onehot_encoder_geo.get_feature_names_out(['Geography']))
geo

Geography_France  Geography_Germany  Geography_Spain
0               0.0                1.0              0.0

In [114]:
df = pd.concat([data.drop('Geography',axis=1),geo],axis=1)

In [115]:
df

CreditScore  Gender  ...  Geography_Germany  Geography_Spain
0            0       1  ...                1.0              0.0

[1 rows x 12 columns]

In [116]:
scaled_df = scaler.transform(df)
scaled_df

array([[-6.73723827,  0.90750738,  3.23510052, -0.6962018 , -1.22589829,
        -2.62934333, -1.55996038, -1.030206  , -1.65233348, -0.99825153,
         1.72916886, -0.57773517]])

In [117]:
prob = model.predict(scaled_df)
prob

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 131ms/step


array([[0.99851424]], dtype=float32)

In [118]:
if(prob>0.5):
    print("He will Exit")
else:
    print("He will not Exit")
    

He will Exit
